theme = "showfolio"
languageCode = "en-us"
baseurl = "https://purschke.berlin"
title = "Johannes Purschke"

[params]
  name = "purschke.berlin"
  description = "Johannes Purschke - Portfolio"
  author = "Johannes Purschke"
  authorEmail = "johannes@purschke.berlin"
  authorImage = "/images/memoji_icon.png"
  autoDarkMode = true

  copyright = "Copyright Â© 2022 - Johannes Purschke Â· All rights reserved"
  # favicon = "/images/favicon/favicon.ico"

[params.homepage]
  title = "Hallo ğŸ‘‹ğŸ¾  Ich bin Johannes Purschke"
  tagline = "Cloud- & Netzwerkadministrator"
  description = "Fachinformatiker fÃ¼r Systemintegration auf der Suche nach einer neuen Herausforderung"
  contact = "mailto:johannes@purschke.berlin"

#[params.homepage.codepen]
#  username = "apvarun"
#  pens = ["MQaRKL", "RxodrP", "BmXGdm", "wdVypQ"]

[params.homepage.resume]
  skills = ["Netzwerkadministration", "Virtualisierung", "Containerisierung", "Linux", "Proxmox", "Ansible", "Microsoft 365 & Azure", "Windows Server", "Active Directory"]

[[params.homepage.resume.work]]
  name = "Mahr EDV"
  role = "IT-Systemadministrator"
  duration = "August 2021 - Juni 2022"

[[params.homepage.resume.work]]
  name = "Cine Plus Media Service"
  role = "IT-Systemadministrator"
  duration = "September 2019 - Juli 2021"

[[params.homepage.resume.education]]
  name = "Ausbildung zum Fachinformatiker fÃ¼r Systemintegration"
  institution = "OSZ IMT"
  duration = "September 2019 - Juni 2022"

[[params.homepage.resume.education]]
  name = "Abitur"
  institution = "BrÃ¶ndby-Oberschule"
  duration = "Jahrgang 2016"

[params.homepage.social]
  linkedin = "https://www.linkedin.com/in/johannespurschke/"
#  github = "https://github.com/officialamatege"
  phone = "tel:+4917677904604"
  mail = "mailto:johannes@purschke.berlin"
[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
